# docker/Dockerfile.api
FROM python:3.11-slim
WORKDIR /app
COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY ../src /app/src
COPY ../models /app/models
COPY ../data /app/data
ENV PYTHONPATH=/app/src
EXPOSE 8000
CMD ["uvicorn", "src.serve.api:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
